In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

4

In [ ]:
b=np.array(([1,2,3],[1,6,7]),dtype=float)
b

array([[1., 2., 3.],
       [1., 6., 7.]])

In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,12).reshape([3,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.random.random([3,3])

array([[0.70244998, 0.78067523, 0.80375275],
       [0.37538343, 0.81119616, 0.01662016],
       [0.6129621 , 0.24625826, 0.1558122 ]])

In [ ]:
#arithmetic operator
a=np.arange(0,5)
a+3
a*3

array([ 0,  3,  6,  9, 12])

In [ ]:
b=np.arange(4,9)
a-b

array([-4, -4, -4, -4, -4])

In [ ]:
#matrix product
A=np.arange(0,9).reshape(3,3)
B=np.arange(10,19).reshape(3,3)

In [ ]:
np.dot(A,B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [ ]:
A.dot(B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [ ]:
np.sqrt(A)
np.log(A)
np.sin(A)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [ ]:
a.sum()
a.min()
a.max()
a.mean()

2.0

In [ ]:
np.apply_along_axis(np.mean,axis=0,arr=A)

array([3., 4., 5.])

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
def foo(x):
  return (x)/2

In [ ]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
#by using ravel ,u can convert 2D array into 1D
np.ravel(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Another important operation is transposing a matrix, which is inverting the columns with the rows. NumPy provides this feature with the transpose() function
np.transpose(A) #its a matrix operation

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
#vstack() function, which combines the second array as new rows of the first array.
np.vstack((A,B))
np.hstack((A,B))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [ ]:
[A1,A2,A3]=np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2]])

In [ ]:
#copying and viewing objects
a=np.array([1,2,3,4])
b=a
a[2]=0
b
c=a.copy()
c

array([1, 2, 0, 4])

In [ ]:
#save and load the data
data_set=([1,2,3,4],[11,12,13,14],[21,22,23,24],[31,32,33,34])
np.save('saved_data',data_set)
loaded_data=np.load('saved_data.npy')
loaded_data

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
data_orders=np.genfromtxt('cars.csv',delimiter=';',names=True)
data_orders     #csv files and numpy
data_orders['Car']